// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// seat_sim_core
List seat_sim_core(NumericMatrix shares, int n_sims, int shift_mode, NumericMatrix shift_mat, NumericVector sd_vec, NumericMatrix chol_t, NumericVector seat_sd_vec, bool has_level, NumericMatrix sd_cell_pre, NumericVector surge_h, IntegerVector surge_party_idx, IntegerVector surge_idx, double surge_floor, double surge_mu, double surge_sd, NumericMatrix cell_mat, LogicalVector cell_has, NumericMatrix ss_mat, LogicalVector ss_has, NumericMatrix pool_mat, bool has_pw, NumericMatrix pw_mat, NumericVector flow_sd_by, double smooth, double fallback_smooth, NumericVector shrink);
RcppExport SEXP _auspol_seat_sim_core(SEXP sharesSEXP, SEXP n_simsSEXP, SEXP shift_modeSEXP, SEXP shift_matSEXP, SEXP sd_vecSEXP, SEXP chol_tSEXP, SEXP seat_sd_vecSEXP, SEXP has_levelSEXP, SEXP sd_cell_preSEXP, SEXP surge_hSEXP, SEXP surge_party_idxSEXP, SEXP surge_idxSEXP, SEXP surge_floorSEXP, SEXP surge_muSEXP, SEXP surge_sdSEXP, SEXP cell_matSEXP, SEXP cell_hasSEXP, SEXP ss_matSEXP, SEXP ss_hasSEXP, SEXP pool_matSEXP, SEXP has_pwSEXP, SEXP pw_matSEXP, SEXP flow_sd_bySEXP, SEXP smoothSEXP, SEXP fallback_smoothSEXP, SEXP shrinkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type shares(sharesSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< int >::type shift_mode(shift_modeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type shift_mat(shift_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd_vec(sd_vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type chol_t(chol_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seat_sd_vec(seat_sd_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type has_level(has_levelSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sd_cell_pre(sd_cell_preSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type surge_h(surge_hSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type surge_party_idx(surge_party_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type surge_idx(surge_idxSEXP);
    Rcpp::traits::input_parameter< double >::type surge_floor(surge_floorSEXP);
    Rcpp::traits::input_parameter< double >::type surge_mu(surge_muSEXP);
    Rcpp::traits::input_parameter< double >::type surge_sd(surge_sdSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cell_mat(cell_matSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type cell_has(cell_hasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ss_mat(ss_matSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type ss_has(ss_hasSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pool_mat(pool_matSEXP);
    Rcpp::traits::input_parameter< bool >::type has_pw(has_pwSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type pw_mat(pw_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type flow_sd_by(flow_sd_bySEXP);
    Rcpp::traits::input_parameter< double >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< double >::type fallback_smooth(fallback_smoothSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type shrink(shrinkSEXP);
    rcpp_result_gen = Rcpp::wrap(seat_sim_core(shares, n_sims, shift_mode, shift_mat, sd_vec, chol_t, seat_sd_vec, has_level, sd_cell_pre, surge_h, surge_party_idx, surge_idx, surge_floor, surge_mu, surge_sd, cell_mat, cell_has, ss_mat, ss_has, pool_mat, has_pw, pw_mat, flow_sd_by, smooth, fallback_smooth, shrink));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_auspol_seat_sim_core", (DL_FUNC) &_auspol_seat_sim_core, 26},
    {NULL, NULL, 0}
};

RcppExport void R_init_auspol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
