# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seat_sim_core <- function(shares, n_sims, shift_mode, shift_mat, sd_vec, chol_t, seat_sd_vec, has_level, sd_cell_pre, surge_h, surge_party_idx, surge_idx, surge_floor, surge_mu, surge_sd, cell_mat, cell_has, ss_mat, ss_has, pool_mat, has_pw, pw_mat, flow_sd_by, smooth, fallback_smooth, shrink) {
    .Call(`_auspol_seat_sim_core`, shares, n_sims, shift_mode, shift_mat, sd_vec, chol_t, seat_sd_vec, has_level, sd_cell_pre, surge_h, surge_party_idx, surge_idx, surge_floor, surge_mu, surge_sd, cell_mat, cell_has, ss_mat, ss_has, pool_mat, has_pw, pw_mat, flow_sd_by, smooth, fallback_smooth, shrink)
}

